# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: [ develop, ci ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Orchd Agent
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.ORCHD_AGENT_GITHUB_ACTIONS }}
          repository: orchd-io/orchd-agent
          ref: master
          path: reqs/orchd-agent
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest wheel pytest-asyncio tox
        python -m pip install /home/runner/work/orchd-sdk/orchd-sdk/reqs/orchd-agent
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start test agent
      run: |
        python -m orchd.app &
        sleep 3
    - name: Test with pytest
      run: |
        tox
    - name: Test build
      run: |
        python setup.py sdist bdist_wheel
    - name: Test deploy
      if: always()
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/


